{% set name = "rst-to-myst" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rst-to-myst-{{ version }}.tar.gz
  sha256: 4d944e1afcd12922a7b8e418558cafc1b5888fba0a2819268c0fd60c2df2f7ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - rst2myst = rst_to_myst.cli:main

requirements:
  host:
    - python >=3.7
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7
    - docutils >=0.15,<0.18
    # for all python so we can stay noarch
    - importlib_resources >=3.1,<4.dev0
    - pyyaml
    - markdown-it-py >=1.0,<2.dev0
    - mdformat >=0.7.6,<0.8.dev0
    - mdformat-myst >=0.1.4,<0.2.dev0
    - mdformat-deflist >=0.1.0,<0.2.dev0
    - click >=7.1,<9

test:
  imports:
    - rst_to_myst
  commands:
    - pip check
    - rst2myst --help
  requires:
    - pip

about:
  home: https://github.com/executablebooks/rst-to-myst
  summary: Convert RST to MyST-Markdown.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/executablebooks/rst-to-myst

extra:
  recipe-maintainers:
    - xylar
